### ISSUE TITLE
Скомпилируй экзешник

### ISSUE THREAD

**Issue by Deamenator** [CyberBiology/Genesis#1]
Сделайте исполняемый файл.

**Comment by CyberBi** [comment]
Окай. скоро))

**Comment by germanow** [comment]
Неплохо было бы какое-то минимальное ридми написать к проекту, а там и сами скомпилируем.

**Comment by CyberBi** [comment]
Скомпилировал исполняемый .jar файл. Лежит в корне. Извините что долго)
