### ISSUE TITLE
Экзешник это хорошо ,А как пользоваться где ридми файл?

### ISSUE THREAD

**Issue by Deamenator** [CyberBiology/Genesis#2]

**Comment by stalker3204** [comment]
В любом текстовом редакторе откройте...

**Comment by Ex10Dios** [comment]
Ну тут не ридми (https://www.youtube.com/watch?v=PCx228KcOow), но объяснение принципов поведения ботов)

**Comment by bigclap** [comment]
Варианты.
1. Устанавливаем java и запускаем ей jar файл из корня проекта.
2. Устанавливаем https://www.jetbrains.com/ru-ru/idea/ там можно сразу и загрузить и собрать проект, и даже с кодом поиграться.

**Comment by CyberBi** [comment]
https://github.com/CyberBiology/Genesis/blob/master/README.md
