### ISSUE TITLE
Error: Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by az09** [CyberBiology/Genesis#3]
Скачал jar, запускаю
```sh
$ java -jar Загрузки/Genesis.jar
```
получаю `Error: Invalid or corrupt jarfile Загрузки/Genesis.jar`

ЧЯДНТ

**Comment by lexakimov** [comment]
В папке c jar файлом выполни java -jar Genesis.jar
Либо полный путь к загрузкам указывай (java -jar C:\Users\username\Downloads\Genesis.jar)

Это всё при условии что в переменную path прописан путь до java

**Comment by CyberBi** [comment]
выложил новый .jar, попробуйте его
